"""add article_interaction table

Revision ID: c8519a37f567
Revises: e13b959353e6
Create Date: 2026-07-10 22:10:31.719987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8519a37f567'
down_revision = 'e13b959353e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_interaction_url_hash'), ['url_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_interaction_url_hash'))

    op.drop_table('article_interaction')
    # ### end Alembic commands ###
