"""add trending_topic table

Revision ID: ca1cee4bf65f
Revises: c8519a37f567
Create Date: 2026-07-11 12:47:16.898491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1cee4bf65f'
down_revision = 'c8519a37f567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('baseline_count', sa.Float(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('articles_json', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trending_topic_topic'), ['topic'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trending_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trending_topic_topic'))

    op.drop_table('trending_topic')
    # ### end Alembic commands ###
